/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverlaysBorderRouteImport } from './routes/overlays/border'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysBorderRoute = OverlaysBorderRouteImport.update({
  id: '/overlays/border',
  path: '/overlays/border',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overlays/border': typeof OverlaysBorderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overlays/border': typeof OverlaysBorderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overlays/border': typeof OverlaysBorderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/overlays/border'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/overlays/border'
  id: '__root__' | '/' | '/overlays/border'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverlaysBorderRoute: typeof OverlaysBorderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/border': {
      id: '/overlays/border'
      path: '/overlays/border'
      fullPath: '/overlays/border'
      preLoaderRoute: typeof OverlaysBorderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverlaysBorderRoute: OverlaysBorderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
