/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverlaysTextRouteImport } from './routes/overlays/text'
import { Route as OverlaysSocialsRouteImport } from './routes/overlays/socials'
import { Route as OverlaysCtaRouteImport } from './routes/overlays/cta'
import { Route as OverlaysCounterRouteImport } from './routes/overlays/counter'
import { Route as OverlaysBorderRouteImport } from './routes/overlays/border'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysTextRoute = OverlaysTextRouteImport.update({
  id: '/overlays/text',
  path: '/overlays/text',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysSocialsRoute = OverlaysSocialsRouteImport.update({
  id: '/overlays/socials',
  path: '/overlays/socials',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysCtaRoute = OverlaysCtaRouteImport.update({
  id: '/overlays/cta',
  path: '/overlays/cta',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysCounterRoute = OverlaysCounterRouteImport.update({
  id: '/overlays/counter',
  path: '/overlays/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysBorderRoute = OverlaysBorderRouteImport.update({
  id: '/overlays/border',
  path: '/overlays/border',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overlays/border': typeof OverlaysBorderRoute
  '/overlays/counter': typeof OverlaysCounterRoute
  '/overlays/cta': typeof OverlaysCtaRoute
  '/overlays/socials': typeof OverlaysSocialsRoute
  '/overlays/text': typeof OverlaysTextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overlays/border': typeof OverlaysBorderRoute
  '/overlays/counter': typeof OverlaysCounterRoute
  '/overlays/cta': typeof OverlaysCtaRoute
  '/overlays/socials': typeof OverlaysSocialsRoute
  '/overlays/text': typeof OverlaysTextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overlays/border': typeof OverlaysBorderRoute
  '/overlays/counter': typeof OverlaysCounterRoute
  '/overlays/cta': typeof OverlaysCtaRoute
  '/overlays/socials': typeof OverlaysSocialsRoute
  '/overlays/text': typeof OverlaysTextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overlays/border'
    | '/overlays/counter'
    | '/overlays/cta'
    | '/overlays/socials'
    | '/overlays/text'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/overlays/border'
    | '/overlays/counter'
    | '/overlays/cta'
    | '/overlays/socials'
    | '/overlays/text'
  id:
    | '__root__'
    | '/'
    | '/overlays/border'
    | '/overlays/counter'
    | '/overlays/cta'
    | '/overlays/socials'
    | '/overlays/text'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverlaysBorderRoute: typeof OverlaysBorderRoute
  OverlaysCounterRoute: typeof OverlaysCounterRoute
  OverlaysCtaRoute: typeof OverlaysCtaRoute
  OverlaysSocialsRoute: typeof OverlaysSocialsRoute
  OverlaysTextRoute: typeof OverlaysTextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/text': {
      id: '/overlays/text'
      path: '/overlays/text'
      fullPath: '/overlays/text'
      preLoaderRoute: typeof OverlaysTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/socials': {
      id: '/overlays/socials'
      path: '/overlays/socials'
      fullPath: '/overlays/socials'
      preLoaderRoute: typeof OverlaysSocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/cta': {
      id: '/overlays/cta'
      path: '/overlays/cta'
      fullPath: '/overlays/cta'
      preLoaderRoute: typeof OverlaysCtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/counter': {
      id: '/overlays/counter'
      path: '/overlays/counter'
      fullPath: '/overlays/counter'
      preLoaderRoute: typeof OverlaysCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays/border': {
      id: '/overlays/border'
      path: '/overlays/border'
      fullPath: '/overlays/border'
      preLoaderRoute: typeof OverlaysBorderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverlaysBorderRoute: OverlaysBorderRoute,
  OverlaysCounterRoute: OverlaysCounterRoute,
  OverlaysCtaRoute: OverlaysCtaRoute,
  OverlaysSocialsRoute: OverlaysSocialsRoute,
  OverlaysTextRoute: OverlaysTextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
